### ISSUE TITLE
Could not open '/lib64/ld-linux-x86-64.so.2' during devcontainer build

### ISSUE THREAD

**Issue by jeremydelacruz** [devcontainers-contrib/features#223]
I'm trying to create a small dev container via VS Code's "Add Dev Container Configuration Files" option. I have selected only a couple other features ("docker-in-docker", "go", "python", and "pre-commit"). 

Every time I select the pre-commit feature (also happens when manually adding the `"ghcr.io/devcontainers-contrib/features/pre-commit:2": {}` feature to the devcontainer.json) I see the following error when trying to build the devcontainer:

```
[2022-12-29T16:13:59.722Z] ------
 > [dev_containers_target_stage 4/9] RUN cd /tmp/build-features/pre-commit_4 && chmod +x ./devcontainer-features-install.sh && ./devcontainer-features-install.sh:
#0 0.134 ===========================================================================
#0 0.134 Feature       : Pre-Commit (via pipx)
#0 0.134 Description   : Pre-Commit is a framework for managing and maintaining multi-language pre-commit hooks.
#0 0.134 Id            : ghcr.io/devcontainers-contrib/features/pre-commit
#0 0.134 Version       : 2.0.0
#0 0.134 Documentation : http://github.com/devcontainers-contrib/features/tree/main/src/pre-commit
#0 0.134 Options       :
#0 0.134     VERSION="latest"
#0 0.134 ===========================================================================
#0 0.792 featmake: OK
#0 0.808 qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
[2022-12-29T16:13:59.722Z] #0 0.810 ERROR: Feature "Pre-Commit (via pipx)" (ghcr.io/devcontainers-contrib/features/pre-commit) failed to install! Look at the documentation at http://github.com/devcontainers-contrib/features/tree/main/src/pre-commit for help troubleshooting this error.
------
[2022-12-29T16:13:59.722Z] ERROR: failed to solve: executor failed running [/bin/sh -c cd /tmp/build-features/pre-commit_4 && chmod +x ./devcontainer-features-install.sh && ./devcontainer-features-install.sh]: exit code: 255
```

For reference I'm running this on a 2021 16-inch MacBookPro with Apple M1 Pro processor (could the error be related to running this on an ARM processor?). Might I be missing something? The devcontainer works fine when removing the pre-commit feature and installing pre-commit manually (using pip3, for example).

**Comment by jcbhmr** [comment]
Here's some more info from around the web on that error message for reference:

> ```sh
> qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
> ```

From this StackOverflow question: https://stackoverflow.com/questions/71040681/qemu-x86-64-could-not-open-lib64-ld-linux-x86-64-so-2-no-such-file-or-direc

<blockquote>

Incidentally, in case it's helpful to another who lands here, I have the same
issue on an M1 Max MacBook Pro laptop attempting to do a `docker build` from a
company repo that should be a pretty well traveled path, but I might be the only
one (it's a small company) that has an ARM64 M1 "Apple Silicon" Mac. **_However
I found the solution (well, a solution) to my situation was exactly the opposite
of the solution to the OP's, and that was to
add_** `--platform=linux/amd64` **_to the FROM line of the docker file._**

Otherwise it was using an ARM64 image to start from without me being the wiser
but then later in the Dockerfile the build attempts to install and execute code
compiled for x86_64. Starting the build process by requesting the base image
be `linux/amd64` ends up with then the base image
having `/lib64/ld-linux-x86-64.so.2`. This probably means everything is being
emulated as x86_64 on the ARM64 CPU via `qemu-x86_64` and so if you have the
option to start from an ARM64 image and can compile within the container during
build time any software you can't install as ARM64 binaries, it'll probably go
faster when you later run the container on the M1 based Mac. I'm not able to try
that myself just yet for this case.

</blockquote>

From this StackOverflow question: https://stackoverflow.com/questions/68630526/lib64-ld-linux-x86-64-so-2-no-such-file-or-directory-error

<blockquote>

If you are running this on an M1 macbook, it's possible that you are running a
native Arm image of ubuntu, instead of the emulated x86 image. If the
elasticsearch distribution you are trying to install is for x86_64, then it
attempts to link to the x86-64-native ld.so, which of course isn't present on
different platforms.

Either install the package for the arm platform specifically if they provide
one, or - more likely - run docker explicitly as the emulated x86_64 platform:

```
docker run --platform linux/x86_64 <image>
```

</blockquote>

**Comment by jeremydelacruz** [comment]
I've seen and dealt with that kind of issue before with other docker images, but I'm trying to use the VS Code built in options and UI for dev containers — not manually running `docker` from CLI, so the flag in this use case doesn't seem ideal. 

Also, I'm curious as to why it might work fine out of the box with all the other features enabled except this one?

**Comment by eitsupi** [comment]
I think this is due to the fact that you are installing the amd64 binary of featmake.
See #246.

**Comment by danielbraun89** [comment]
Should be fixed now that featmake and oras usage has been deprecated. Installation of pre-commit feature should be ARM compatible as any utility (including featmake`s replacement - dcontainer) is being installed on ARM as vanila pipx install, instead of a binary.
