### ISSUE TITLE
[Feature Request]: How to setup local dev environment

### ISSUE THREAD

**Issue by ccavolt** [devcontainers-contrib/features#388]
### Requested Feature

Apologies in advance if I'm missing something obvious, but I've been trying to test locally (well, in a Codespace) before submitting pull requests and don't seem to be able to do so. Here are the issues I've run into so far:

- The devcontainer image specified (mcr.microsoft.com/devcontainers/universal:linux) requires a minimum Codespace size of 8 core/16 GB RAM/64 GB storage because anything smaller runs out of space just setting up the Codespace. While this isn't necessarily a problem, I didn't see any guidance indicating this and had to figure it out myself. Adding a hostRequirements section in devcontainer.json would fix this.
- Even using a sufficiently large Codespace, I'm unable to run any of the tests using the devcontainer CLI. For any feature, it just says "Failed to launch container". I end up committing something that hopefully works in my fork and then running the tests via GitHub Actions, which isn't a great feedback loop.
- Via [a fork I made](https://github.com/ccavolt/features/tree/devcontainer-reqs), I've been able to run tests for certain features, on the smallest size Codespace. The first one I ran, erlang-asdf, fails with some error regarding nanolayer, but act-asdf and ansible run the tests successfully.

All that to say, any guidance you can give on how to create a working local dev environment is greatly appreciated!

**Comment by nikaro** [comment]
By the way, `mcr.microsoft.com/devcontainers/universal:linux` image does not seem to be compatible with ARM64 (i'm on a Apple M1 ship):
```
[128224 ms] Start: Run: docker inspect --type image mcr.microsoft.com/devcontainers/universal:linux
[128430 ms] Error fetching image details: No manifest found for mcr.microsoft.com/devcontainers/universal:linux.
[128430 ms] Start: Run: docker pull mcr.microsoft.com/devcontainers/universal:linux
linux: Pulling from devcontainers/universal
no matching manifest for linux/arm64/v8 in the manifest list entries
[128767 ms] []
[128767 ms] Error response from daemon: No such image: mcr.microsoft.com/devcontainers/universal:linux
[128767 ms] Command failed: docker inspect --type image mcr.microsoft.com/devcontainers/universal:linux
[128773 ms] Exit code 1
```

**Comment by danielbraun89** [comment]
Due to your feedback I have replaced `mcr.microsoft.com/devcontainers/universal:linux` with the slimmer `mcr.microsoft.com/devcontainers/base:ubuntu`  (also should support arm64 as per https://github.com/microsoft/vscode-dev-containers/issues/558)

Regarding the erlang test failing - you found a bug :) (it was not discovered in the regular ci tests as they force scenarios only (using the `--skip-autogenerated` command in order to explicitely use the testbed container - which is `base:debian` in which the bug does not occur). I have regenerate the feature with a fix - newest version should pass the vanila test
