### ISSUE TITLE
[Bug]: localstack devcontainer feature seems to be broken

### ISSUE THREAD

**Issue by frankpengau** [devcontainers-contrib/features#398]
### Feature id and version

ghcr.io/devcontainers-contrib/features/localstack:2

### Devcontainer base Image

mcr.microsoft.com/devcontainers/base:jammy

### What happened?

While trying to install localstack devcontainer feature within Ubuntu 22.04 (jammy), it would timeout and fail with exit code 1 for the step `installing localstack from spec 'localstack[full]'`.

```
	"image": "mcr.microsoft.com/devcontainers/base:jammy",
	"features": {
		"ghcr.io/devcontainers-contrib/features/localstack:2": {}
	}
```

I had a look and it could be due to the recent merge for the nanolayer change from v0.4.27 to v0.4.29 or even before that change: https://github.com/devcontainers-contrib/features/actions/runs/4821510340/jobs/8587523454

**Version Info**
VSCode: 
```
Version: 1.77.1 (Universal)
Commit: b7886d7461186a5eac768481578c1d7ca80e2d21
Date: 2023-04-04T23:23:33.779Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 22.4.0
Sandboxed: No
```
OS: 
```
macOS Ventura 13.3.1 (22E261)
```

`uname -a`:
```
Darwin HF0013753 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 21:01:02 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T8112 arm64
```

Full Logs: https://github.com/frankpengau/vscode-devcontainer-localstack/blob/main/logs/remoteContainers-2023-04-30T02-55-33.988Z.log

### Relevant log output

```shell
 => [dev_containers_target_stage 5/5] RUN --mount=type=bind,from=dev_co  387.5s
 => => # oIqcyAn7g/nanolayer" bash  -i  +H ./install.sh' failed. error: Return 
 => => # Code: 1. see logs for details.                                        
 => => # ERROR: Feature "Localstack (via pipx)" (ghcr.io/devcontainers-contrib/
 => => # features/localstack) failed to install! Look at the documentation at h
 => => # ttp://github.com/devcontainers-contrib/features/tree/main/src/lo
[2023-04-30T03:02:07.084Z] calsta
[2023-04-30T03:02:07.084Z]  => => # ck for help troubleshooting this error. 
 => => # ��� installing localstack from spec 'localstack[full]'
```

**Comment by danielbraun89** [comment]
@frankpengau  thanks for posting such a detailed report!
As it tuned out there were actually two problems with the localstack feature:

1. Apparently, `localstack` is the main python package, but the python console scripts is defined in a another package called `localstack-core`. when installing using pipx, only `localstack` was exposed, and since it has no console scripts, pipx throw an installation error. The solution was to upgrade the pipx-package feature in order to accept a new option called `includeDeps` (defaults to false) which will then include the `--include-deps` flag in the pipx installation command.  This will result in exposing the localstack-core. 

2. Since the feature installs localstack for the final user which may not be root, localstack may dont have permissions for the `/var/lib/localstack` folder (this is the case when installing in github codespaces for example) 
The fix was to precreate this folder and chown to the remote user 

Please try the fixed localstack feature:  
`ghcr.io/devcontainers-contrib/features/localstack:2.0.18`

**Comment by frankpengau** [comment]
@danielbraun89 thank you for the detailed explanation! I shall give it a go and report back on the status.

**Comment by frankpengau** [comment]
@danielbraun89 localstack installs successfully now, but I haven't got it to start via `localstack start`. I think I'm just missing the docker-in-docker (dind) feature, in order to get it to run.

**Comment by frankpengau** [comment]
I can confirm that localstack starts properly with dind included as part of the features. 

```
"image": "mcr.microsoft.com/devcontainers/base:jammy",
	"features": {
		"ghcr.io/devcontainers-contrib/features/localstack:2.0.18": {},
		"ghcr.io/devcontainers/features/docker-in-docker:2": {}
	}
```

It might be worth it to include it in the `installsAfter` section of the `devcontainer-feature.json`: https://github.com/devcontainers-contrib/features/blob/main/src/localstack/devcontainer-feature.json#L17

**Comment by frankpengau** [comment]
Created a PR for the potential change, if you think it makes sense, otherwise happy to have it closed.

PR: https://github.com/devcontainers-contrib/features/pull/401
